Develop
lu-lay/MontyHall3doors pull request #2
Opened 2020-08-27 16:54 UTC by lu-lay

2020-08-30 05:55 UTC, kangraemin requested changes

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +    var finalSelect = 0
변수 네이밍 규칙을 통일성 있게 해주세요 ( snake_case 또는 camel case 중 한가지만 써주세요 ) 일반적으로는 Camel case가 일반적인 변수 네이밍에 더 많이 쓰이는것 같아요.

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +        btn_view_results.setOnClickListener(btn_event)
각 버튼을 눌렀을 때 실행되는 기능을 한가지 함수에 몰아 넣은 뒤 함수 안에서 처리 해 주고 있어요.
 각 버튼을 클릭 해했을때 동작하는 함수가 버튼마다 다르기 때문에 각 버튼마다 동작하는 함수를 다르게 하는것이 가독성이 좀 더 좋아보여요

그리고 클릭 리스너를 상속받은 BtnEvent라는 구현체를 만들어 사용하는 이유가 있나요 ?

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +    fun rnds() {
다른 곳에서 사용하지 않는다면 private 을 붙여 줘도 될 것 같아요 ( 밑의 다른 메서드들 모두 )

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +        Selection2.visibility = View.GONE
랜덤 값을 생성 해주는 함수와 별개의 동작처럼 보여요. initializeView() 라는 함수로 분리 해주는 것이 어떨까요 ?

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +    fun Start_rnds() {
메서드의 이름을 규칙성 있게 지어주세요

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +                img_door3_back.visibility = View.VISIBLE
```Kotlin
img_door2_back.setImageResource(R.drawable.supercar_64)
img_door1_back.setImageResource(R.drawable.goat_64)
img_door3_back.setImageResource(R.drawable.goat_64)
img_door2_back.visibility = View.VISIBLE
```
부분이 반복 되는것 같아요 하나의 메서드로 분리 해 줄 수 있을것 같아요

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +        }
```Kotlin
Selection0.visibility = View.GONE
Selection1.visibility = View.GONE
Selection2.visibility = View.VISIBLE
```
이부분도 계속 반복 되는것 같아요 하나의 메서드로 분리 해줄 수 있을 것 같아요

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +    private fun Popup() {
메서드의 이름을 규칙성 있게 지어주세요

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +        val Percent = String.format("%.2f", percentage)
변수 네이밍 규칙성 통일

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +            }
dialog, which가 쓰이지 않았다면, `_, _`로 수정 해 주세요

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +
전반적으로 if 뷰의 visibility를 기준으로 앱의 단계를 분기 해 주고 있는것 같아요. 앱의 단계를 표시하는 변수를 하나 두고, 해당 변수를 통해 분기를 해주면 가독성이 더 좋을 것 같아요.

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +                                    }
이부분 코드가 계속해서 반복 호출 되는 것 같아요. 하나의 메서드로 분리 해줄 수 있을 것 같아요.

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +                                Selection0.visibility.equals(View.VISIBLE) -> {
`equals` -> `==`

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +                            }
Select 변수가 이전에 유저가 선택한 값을 의미하는 것이라면 Select 변수의 네이밍을 변경 해 줄 필요성이 있어보여요

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +
의미없는 공백은 제거 해주세요 ( 전반적인 코드 모두에 )

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +                            btn_view_results.visibility = View.VISIBLE
이부분도 메서드로 분리 해 줄 수 있을것 같아요

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +                            }
```Kotlin
when (View.VISIBLE) {
    Selction0.visibility -> {
        finalSelect = 0
    }
    Selection1.visibility -> {
        finalSelect = 1
    }
    Selection2.visibility -> {
        finalSelect = 2
    }
}
```

띄어쓰기를 통일 해 주세요

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +                            }
최종적으로 유저가 자동차를 선택 했는지 안했는지을 알아보기 위한 분기라면, drawable을 직접 가져와서 비교 하는 것 보다 더 좋은 방법이 있을 것 같아요. 

띄어쓰기 통일 해 주세요

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/LastQuestion"
id naming convention 통일

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/res/layout/activity_main.xml
> +        android:visibility="visible"
이부분을 추가한 이유가 있나요 ?

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/door0"
id naming convention 통일

2020-08-30 05:55 UTC, kangraemin commented on app/src/main/res/values/strings.xml
> +    <string name="Main_view_results_btn">결과보기</string>
`Main` -> `main` ( snake_case )

2020-09-03 18:13 UTC, lu-lay commented on app/src/main/res/values/strings.xml
> +    <string name="Main_view_results_btn">결과보기</string>
수정 했습니다.

2020-09-03 18:32 UTC, lu-lay commented on app/src/main/res/values/strings.xml
> +    <string name="Main_view_results_btn">결과보기</string>
수정 했습니다 커밋 메시지 Modified String Naming (snake_case) to Strng <- 오타 있음

2020-09-03 18:38 UTC, lu-lay commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/door0"
수정 했습니다 커밋 메시지 Modified View Naming(snack_case) to Main Xml

2020-09-03 18:57 UTC, lu-lay commented on app/src/main/res/layout/activity_main.xml
> +        android:visibility="visible"
XML 구성 당시 3개의 question 모두 visibility 기능을 필요 하여 삽입 하였으며
 Kotlin 에서 해당 기능이 추가되어 3개의 question 모두  visibility 기능 삭제 하였습니다.

2020-09-03 19:00 UTC, kimriri commented on app/src/main/res/values/strings.xml
> +    <string name="Main_view_results_btn">결과보기</string>
snake_case로 수정 하였습니다.

2020-09-03 19:02 UTC, lu-lay commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/door0"
snake_case  naming convention  통일 하였습니다.

2020-09-03 19:02 UTC, lu-lay commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/LastQuestion"
snake_case naming convention 통일 하였습니다.

2020-09-03 20:36 UTC, lu-lay commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +                            }
수정 하였습니다.

2020-09-03 21:04 UTC, lu-lay commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +        btn_view_results.setOnClickListener(btn_event)
버튼들을 각각 OnClickListener 를 생성 하는 것 보다 하나의 함수에서 관리 하는 게 메모리 효율적으로 좋다고 생각했고 가독성이 더 좋을 거라고 판단 했습니다.
메모리 효율이 좋을 거라고 생각한 이유는 계속해서 OnClickListener 함수를  생성할 필요 없이 하나의 함수 안에 작성되기 때문이고 가독성이 좋다고 생각한 이유는 개인적인 의견으로 버튼 기능을 하는  함수들 사이에 다른 함수들이 끼여 있으면 코드를 읽기가 불편해 져서 입니다.

2020-09-03 21:09 UTC, lu-lay commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +            }
수정 하였습니다.

2020-09-08 17:29 UTC, lu-lay commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +    fun Start_rnds() {
수정 하였습니다.

2020-09-08 17:30 UTC, lu-lay commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +        Selection2.visibility = View.GONE
수정 하였습니다.

2020-09-08 17:30 UTC, lu-lay commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +    fun rnds() {
수정하였습니다.

2020-09-08 17:50 UTC, lu-lay commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +        btn_view_results.setOnClickListener(btn_event)
수정완료

2020-09-08 17:50 UTC, lu-lay commented on app/src/main/java/ko/co/montyhall3doors/MainActivity.kt
> +    var finalSelect = 0
Camel caes 로 수정 하였습니다.

2020-09-15 17:35 UTC, merged